xcodeproj 'Yaga.xcodeproj'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'Realm'
pod 'AFNetworking', '~> 2.0'
pod 'APAddressBook', '~> 0.0.7'
pod 'libPhoneNumber-iOS', '~> 0.7'
pod 'SwipeView', '~> 1.3.2'
pod 'FrameAccessor', '~> 1.0'
pod 'FLAnimatedImage'
pod 'NSDate-Time-Ago', :inhibit_warnings => true
pod 'SVPullToRefresh'
